### ISSUE TITLE
「评论」GitHub Actions 实现自动部署静态博客

### ISSUE THREAD

**Issue by xugaoyi** [xugaoyi/blog-gitalk-comment#43]
页面：https://xugaoyi.com/pages/6b9d359ec5aa5019/

**Comment by SaulJWu** [comment]
现在这种发布方式还适用吗？

**Comment by xugaoyi** [comment]
> 现在这种发布方式还适用吗？

适用。但有更好的部署方式，部署到https://vercel.com/ 访问速度更快

**Comment by SaulJWu** [comment]
> @xugaoyi
> > 现在这种发布方式还适用吗？
> 
> 适用。但有更好的部署方式，部署到https://vercel.com/ 访问速度更快

我刚才试了一下，现在这种不行了。。。

更好的部署方式，有最佳实践嘛

**Comment by xugaoyi** [comment]
> @SaulJWu
> 我刚才试了一下，现在这种不行了。。。
> 
> 更好的部署方式，有最佳实践嘛

百度上有很多文章

**Comment by SaulJWu** [comment]
> > @SaulJWu
> > 我刚才试了一下，现在这种不行了。。。
> > 更好的部署方式，有最佳实践嘛
> 
> 百度上有很多文章

经过一些测试，自动触发成功了，只需要把`BUILD_SCRIPT`的抽离成一个步骤就可以了，姿势为：
```yml
name: CI

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps: # 步骤
      - name: Checkout 🛎️
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本

      - name: run deploy.sh # 步骤3 （同时部署到github和coding）
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
          # CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: npm install && npm run deploy

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          cd docs/.vuepress/dist
          cd -

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
        # env: # 设置环境变量
        #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
        #   BASE_BRANCH: master # 要部署的文件夹所在的分支.
        #   BRANCH: gh-pages # 部署到的分支
        #   FOLDER: docs/.vuepress/dist # 要部署的文件夹.
        # BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist  && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）


```

![image-20211113124307797](https://gitee.com/SaulJWu/blog-images/raw/master/images/20211113124314.png)
